language: csharp

script:

  - xbuild /p:Configuration=Debug GF.sln

before_install:

  - sudo apt-get install nunit-console

before_script:

  - nuget restore GF.sln

after_script:

- nunit-console GF/bin/Debug/GF.exe
